# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Xilinx/Projects/ip_repo/sha512_1.0/sha512_v1_0_project/sha512_v1_0_project.cache/wt [current_project]
set_property parent.project_path F:/Xilinx/Projects/ip_repo/sha512_1.0/sha512_v1_0_project/sha512_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  f:/Xilinx/Projects/ip_repo/sha512_1.0
  f:/Xilinx/Projects/ip_repo/sha3_1.0
} [current_project]
read_verilog -library xil_defaultlib {
  F:/Xilinx/Projects/ip_repo/sha512_1.0/sha512_v1_0_project/sha512_v1_0_project.srcs/sources_1/imports/rtl/sha512_k_constants.v
  F:/Xilinx/Projects/ip_repo/sha512_1.0/sha512_v1_0_project/sha512_v1_0_project.srcs/sources_1/imports/rtl/sha512_h_constants.v
  F:/Xilinx/Projects/ip_repo/sha512_1.0/sha512_v1_0_project/sha512_v1_0_project.srcs/sources_1/imports/rtl/sha512_w_mem.v
  F:/Xilinx/Projects/ip_repo/sha512_1.0/sha512_v1_0_project/sha512_v1_0_project.srcs/sources_1/imports/rtl/sha512_core.v
  F:/Xilinx/Projects/ip_repo/sha512_1.0/hdl/sha512_v1_0_S00_AXI.v
  F:/Xilinx/Projects/ip_repo/sha512_1.0/sha512_v1_0_project/sha512_v1_0_project.srcs/sources_1/imports/rtl/sha512.v
  F:/Xilinx/Projects/ip_repo/sha512_1.0/hdl/sha512_v1_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top sha512_v1_0 -part xc7z010clg400-1


write_checkpoint -force -noxdef sha512_v1_0.dcp

catch { report_utilization -file sha512_v1_0_utilization_synth.rpt -pb sha512_v1_0_utilization_synth.pb }
