# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/Pre/Pre.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pre || ORIG_REF_NAME==Pre}]

# IP: ip/MACC/MACC.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MACC || ORIG_REF_NAME==MACC}]

# IP: ip/Fin/Fin.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Fin || ORIG_REF_NAME==Fin}]

# IP: ip/Acc/Acc.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Acc || ORIG_REF_NAME==Acc}]

# IP: ip/Reduce/Reduce.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Reduce || ORIG_REF_NAME==Reduce}]

# IP: ip/AddSub/AddSub.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AddSub || ORIG_REF_NAME==AddSub}]

# IP: ip/DPBRAM/DPBRAM.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBRAM || ORIG_REF_NAME==DPBRAM}]
