# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Xilinx/Projects/trial_import/trial_import.cache/wt [current_project]
set_property parent.project_path F:/Xilinx/Projects/trial_import/trial_import.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths f:/Xilinx/Projects/trial_import [current_project]
add_files F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/DPBRAM/bram.coe
read_ip -quiet F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/Pre/Pre.xco
set_property is_locked true [get_files F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/Pre/Pre.xco]

read_ip -quiet F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/MACC/MACC.xco
set_property is_locked true [get_files F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/MACC/MACC.xco]

read_ip -quiet F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/Fin/Fin.xco
set_property is_locked true [get_files F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/Fin/Fin.xco]

read_ip -quiet F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/Acc/Acc.xco
set_property is_locked true [get_files F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/Acc/Acc.xco]

read_ip -quiet F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/Reduce/Reduce.xco
set_property is_locked true [get_files F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/Reduce/Reduce.xco]

read_ip -quiet F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/AddSub/AddSub.xco
set_property is_locked true [get_files F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/AddSub/AddSub.xco]

read_ip -quiet F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/DPBRAM/DPBRAM.xco
set_property is_locked true [get_files F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/ip/DPBRAM/DPBRAM.xco]

read_verilog -library xil_defaultlib {
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/hdl/ed_keygen_trial_v1_0_S00_AXI.v
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/hdl/ed_keygen_trial_v1_0.v
}
read_vhdl -library xil_defaultlib {
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/DSP_Multiply_Prereduction.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/DSP_Multiply_Operation.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/DSP_Accumulate_Reduction.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/DSP_Accumulate_Operation.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/CarryEstimator.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/StoreUnit.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/RotateUnit.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/MultiplyUnit.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/MulRegister.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/LoadUnit.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/DSP_Addition_Reduction.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/DSP_Addition_Operation.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/Accumulate.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/MultiplicationUnit.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/Flag_Register.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/BRAM_DualPort.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/AdditionUnit.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/LSR255.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/ArithmeticUnit.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/Counter.vhd
  F:/Xilinx/Projects/trial_import/trial_import.srcs/sources_1/imports/sources/Curve25519Core.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top ed_keygen_trial_v1_0 -part xc7z020clg484-3


write_checkpoint -force -noxdef ed_keygen_trial_v1_0.dcp

catch { report_utilization -file ed_keygen_trial_v1_0_utilization_synth.rpt -pb ed_keygen_trial_v1_0_utilization_synth.pb }
